vich_uploader:
    db_driver: orm

    mappings:
         campaign_bo:
           uri_prefix: /uploads/campaigns/bos
           upload_destination: '%kernel.project_dir%/public/uploads/campaigns/bos'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
         campaign_brief:
           uri_prefix: /uploads/campaigns/briefs
           upload_destination: '%kernel.project_dir%/public/uploads/campaigns/briefs'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
         campaign_lineItemsFile:
           uri_prefix: /uploads/campaigns/lineitems
           upload_destination: '%kernel.project_dir%/public/uploads/campaigns/lineitems'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
         
           
